// apps/client-ui/src/app/dashboard/shared/instrument-search.component.ts
import { CurrencyPipe } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  booleanAttribute,
  computed,
  input,
  output,
  signal,
} from '@angular/core';
import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideSearch } from '@ng-icons/lucide';
import { Instrument, searchInstruments } from '../mock-data';
import { SignedPercentPipe } from './signed-percent.pipe';

let nextId = 0;

@Component({
  selector: 'app-instrument-search',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [NgIcon, CurrencyPipe, SignedPercentPipe],
  providers: [provideIcons({ lucideSearch })],
  host: { class: 'relative block' },
  template: `
    <div class="relative">
      <label [for]="inputId" class="sr-only">Search instruments</label>
      <ng-icon
        name="lucideSearch"
        class="text-muted-foreground pointer-events-none absolute top-1/2 left-4 -translate-y-1/2"
        [class]="size() === 'lg' ? 'text-[24px]' : 'text-[16px]'"
      />
      <input
        [id]="inputId"
        type="search"
        role="combobox"
        autocomplete="off"
        placeholder="Search"
        [class]="inputClasses()"
        [value]="query()"
        [attr.aria-expanded]="open()"
        [attr.aria-controls]="listId"
        [attr.aria-activedescendant]="open() ? optionId(activeIndex()) : null"
        (input)="onInput($event)"
        (focus)="focused.set(true)"
        (blur)="focused.set(false)"
        (keydown)="onKeydown($event)"
      />
    </div>

    @if (open()) {
      <ul [id]="listId" role="listbox" [class]="resultsClasses()">
        @for (instrument of results(); track instrument.symbol; let i = $index) {
          <li
            [id]="optionId(i)"
            role="option"
            [attr.aria-selected]="i === activeIndex()"
            class="flex cursor-pointer items-center justify-between gap-4 px-4 py-2"
            [class.bg-muted]="i === activeIndex()"
            (mousedown)="$event.preventDefault()"
            (mouseenter)="activeIndex.set(i)"
            (click)="select(instrument)"
          >
            <span class="min-w-0">
              <span class="block font-semibold">{{ instrument.symbol }}</span>
              <span class="text-muted-foreground block truncate text-xs">{{
                instrument.name
              }}</span>
            </span>
            <span class="shrink-0 text-right">
              <span class="block">{{ instrument.price | currency: 'USD' }}</span>
              <span
                class="block text-xs"
                [class]="instrument.changePercent >= 0 ? 'text-gain' : 'text-loss'"
              >
                {{ instrument.changePercent | signedPercent }}
              </span>
            </span>
          </li>
        } @empty {
          <li class="text-muted-foreground px-4 py-2 text-sm">
            No instruments match "{{ query() }}"
          </li>
        }
      </ul>
    }
  `,
})
export class InstrumentSearchComponent {
  readonly size = input<'md' | 'lg'>('md');
  readonly embedded = input(false, { transform: booleanAttribute });
  readonly instruments = input<readonly Instrument[]>([]);
  readonly selected = output<Instrument>();

  protected readonly query = signal('');
  protected readonly focused = signal(false);
  protected readonly activeIndex = signal(0);

  protected readonly results = computed(() => {
    const instruments = this.instruments();
    return instruments.length
      ? searchInstruments(this.query(), instruments)
      : searchInstruments(this.query());
  });
  protected readonly open = computed(() => this.focused() && this.query().trim().length > 0);
  protected readonly inputClasses = computed(() => {
    const size = this.size() === 'lg' ? 'h-[70px] pr-4 pl-14 text-2xl' : 'h-11 pr-4 pl-11 text-sm';
    const base =
      'border-border placeholder:text-muted-foreground focus-visible:border-ring w-full border transition-colors outline-none';
    return this.embedded()
      ? `${base} ${size} rounded-none border-x-0 border-t-0 bg-transparent`
      : `${base} ${size} bg-card rounded-xl`;
  });
  protected readonly resultsClasses = computed(() =>
    this.embedded()
      ? 'max-h-64 overflow-y-auto py-1'
      : 'border-border bg-popover absolute inset-x-0 top-full z-20 mt-1 max-h-80 overflow-y-auto rounded-[5px] border py-1 shadow-lg',
  );

  private readonly _id = nextId++;
  protected readonly inputId = `instrument-search-${this._id}`;
  protected readonly listId = `${this.inputId}-results`;

  protected optionId(index: number): string {
    return `${this.listId}-${index}`;
  }

  protected onInput(event: Event): void {
    this.query.set((event.target as HTMLInputElement).value);
    this.activeIndex.set(0);
  }

  protected onKeydown(event: KeyboardEvent): void {
    const count = this.results().length;
    switch (event.key) {
      case 'ArrowDown':
        event.preventDefault();
        if (count) this.activeIndex.update((i) => (i + 1) % count);
        break;
      case 'ArrowUp':
        event.preventDefault();
        if (count) this.activeIndex.update((i) => (i - 1 + count) % count);
        break;
      case 'Enter': {
        const instrument = this.results()[this.activeIndex()];
        if (this.open() && instrument) {
          event.preventDefault();
          this.select(instrument);
        }
        break;
      }
      case 'Escape':
        if (this.query()) {
          // Clear the search without also closing an enclosing dialog.
          event.stopPropagation();
          this.query.set('');
        }
        break;
    }
  }

  protected select(instrument: Instrument): void {
    this.query.set('');
    this.selected.emit(instrument);
  }
}

// designs/sean-graph/components/market/InstrumentSearch.jsx
import React, { useState } from 'react';
import { Icon } from '../core/Icon.jsx';

const money = (v) => '$' + v.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const pct = (v) => (v >= 0 ? '+' : '') + v.toFixed(2) + '%';

// app-instrument-search: combobox with symbol/name/price/change rows.
export function InstrumentSearch({ instruments = [], onSelect, size = 'md', placeholder = 'Search', style }) {
  const [q, setQ] = useState('');
  const [focus, setFocus] = useState(false);
  const [active, setActive] = useState(0);
  const term = q.trim().toLowerCase();
  const results = term ? instruments.filter((i) => i.symbol.toLowerCase().includes(term) || i.name.toLowerCase().includes(term)) : [];
  const open = focus && term.length > 0;
  const lg = size === 'lg';
  const pick = (i) => { setQ(''); onSelect && onSelect(i); };
  const key = (e) => {
    if (e.key === 'ArrowDown') { e.preventDefault(); results.length && setActive((active + 1) % results.length); }
    else if (e.key === 'ArrowUp') { e.preventDefault(); results.length && setActive((active - 1 + results.length) % results.length); }
    else if (e.key === 'Enter' && open && results[active]) { e.preventDefault(); pick(results[active]); }
    else if (e.key === 'Escape') setQ('');
  };
  return (
    <div style={{ position: 'relative', display: 'block', ...style }}>
      <Icon name="search" size={lg ? 24 : 16} style={{ position: 'absolute', left: 16, top: lg ? 35 : 22, transform: 'translateY(-50%)', color: 'var(--muted-foreground)', pointerEvents: 'none' }} />
      <input type="search" role="combobox" aria-expanded={open} autoComplete="off" placeholder={placeholder} value={q}
        onChange={(e) => { setQ(e.target.value); setActive(0); }} onFocus={() => setFocus(true)} onBlur={() => setFocus(false)} onKeyDown={key}
        style={{ width: '100%', height: lg ? 70 : 44, padding: lg ? '0 16px 0 56px' : '0 16px 0 44px', fontSize: lg ? 24 : 14, borderRadius: 12, border: '1px solid ' + (focus ? 'var(--ring)' : 'var(--border)'), background: 'var(--card)', color: 'var(--foreground)', outline: 'none', transition: 'border-color 150ms' }} />
      {open ? (
        <ul role="listbox" style={{ position: 'absolute', left: 0, right: 0, top: '100%', zIndex: 20, marginTop: 4, maxHeight: 320, overflowY: 'auto', listStyle: 'none', padding: '4px 0', borderRadius: 5, border: '1px solid var(--border)', background: 'var(--popover)', boxShadow: 'var(--shadow-lg)' }}>
          {results.length ? results.map((i, idx) => (
            <li key={i.symbol} role="option" aria-selected={idx === active} onMouseDown={(e) => e.preventDefault()} onMouseEnter={() => setActive(idx)} onClick={() => pick(i)}
              style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 16, padding: '8px 16px', cursor: 'pointer', background: idx === active ? 'var(--muted)' : 'transparent' }}>
              <span style={{ minWidth: 0 }}>
                <span style={{ display: 'block', fontWeight: 600, fontSize: 14 }}>{i.symbol}</span>
                <span style={{ display: 'block', fontSize: 12, color: 'var(--muted-foreground)', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{i.name}</span>
              </span>
              <span style={{ flexShrink: 0, textAlign: 'right', fontSize: 14 }}>
                <span style={{ display: 'block' }}>{money(i.price)}</span>
                <span style={{ display: 'block', fontSize: 12, color: i.changePercent >= 0 ? 'var(--color-gain)' : 'var(--color-loss)' }}>{pct(i.changePercent)}</span>
              </span>
            </li>
          )) : <li style={{ padding: '8px 16px', fontSize: 14, color: 'var(--muted-foreground)' }}>No instruments match "{q}"</li>}
        </ul>
      ) : null}
    </div>
  );
}
